-- Convert tenant-bound staff logins into global accounts. Canonical email
-- collisions must be resolved deliberately rather than merging credentials.
BEGIN;

-- Keep the orphan-instructor snapshot and all account/session backfills stable
-- until the new foreign keys and uniqueness constraints are in place.
-- Readers may continue until an individual ALTER TABLE needs its stronger DDL
-- lock; writes and concurrent schema changes remain blocked for consistency.
SET LOCAL lock_timeout = '10s';
LOCK TABLE "Business", "User", "Instructor", "AuthSession", "Customer", "Participant"
  IN SHARE ROW EXCLUSIVE MODE;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM "User"
    GROUP BY lower(btrim("email"))
    HAVING count(*) > 1
  ) THEN
    RAISE EXCEPTION 'Cannot normalize User.email: duplicate canonical email addresses exist';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM "User"
    WHERE btrim("email") = ''
  ) THEN
    RAISE EXCEPTION 'Cannot normalize User.email: blank email address exists';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM "Customer"
    GROUP BY "businessId", lower(btrim("email"))
    HAVING count(*) > 1
  ) THEN
    RAISE EXCEPTION 'Cannot normalize Customer.email: duplicate canonical email addresses exist within a business';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM "Customer"
    WHERE btrim("email") = ''
  ) THEN
    RAISE EXCEPTION 'Cannot normalize Customer.email: blank email address exists';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM "User"
    WHERE upper(btrim("role")) NOT IN ('OWNER', 'ADMIN', 'COACH')
  ) THEN
    RAISE EXCEPTION 'Cannot migrate User.role: unsupported legacy role exists';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM "User" AS account
    JOIN "Instructor" AS instructor ON instructor."id" = account."instructorId"
    WHERE instructor."businessId" <> account."businessId"
  ) THEN
    RAISE EXCEPTION 'Cannot migrate User.instructorId: instructor belongs to another business';
  END IF;
END $$;

UPDATE "User"
SET "email" = lower(btrim("email")),
    "role" = upper(btrim("role"));

UPDATE "Customer"
SET "email" = lower(btrim("email"));

-- The ordinary unique index is sufficient once every stored address is
-- canonical and the database rejects future mixed-case or padded variants.
ALTER TABLE "User" ADD CONSTRAINT "User_email_canonical_check"
  CHECK ("email" <> '' AND "email" = lower(btrim("email")));
ALTER TABLE "Customer" ADD CONSTRAINT "Customer_email_canonical_check"
  CHECK ("email" <> '' AND "email" = lower(btrim("email")));

-- Expand the global account before moving tenant-specific access into
-- Membership. passwordHash is nullable for accounts that are not yet claimed.
ALTER TABLE "User"
  ADD COLUMN "accountType" TEXT,
  ADD COLUMN "phone" TEXT NOT NULL DEFAULT '',
  ADD COLUMN "parentName" TEXT NOT NULL DEFAULT '',
  ALTER COLUMN "passwordHash" DROP NOT NULL;

UPDATE "User"
SET "accountType" = CASE
  WHEN "role" = 'OWNER' THEN 'OWNER'
  ELSE 'COACH'
END;

ALTER TABLE "User"
  ALTER COLUMN "accountType" SET NOT NULL,
  ALTER COLUMN "accountType" SET DEFAULT 'CUSTOMER',
  ADD CONSTRAINT "User_accountType_check"
    CHECK ("accountType" IN ('CUSTOMER', 'COACH', 'OWNER'));

-- Membership IDs reuse the old user IDs for a deterministic backfill without
-- relying on a database-side CUID generator. New IDs are generated by Prisma.
CREATE TABLE "Membership" (
  "id" TEXT NOT NULL,
  "userId" TEXT NOT NULL,
  "businessId" TEXT NOT NULL,
  "role" TEXT NOT NULL,
  "instructorId" TEXT,
  "active" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "Membership_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "Membership_role_check" CHECK ("role" IN ('OWNER', 'ADMIN', 'COACH'))
);

INSERT INTO "Membership" (
  "id", "userId", "businessId", "role", "instructorId", "active", "createdAt"
)
SELECT
  "id", "id", "businessId", "role", "instructorId", true, "createdAt"
FROM "User";

-- Preserve every legacy roster entry in the account architecture. Instructors
-- without an old staff login receive an explicitly unclaimed account: the
-- placeholder address cannot receive mail and the null password cannot log in.
-- A later verified staff-link flow can replace this placeholder safely.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM "Instructor" AS instructor
    LEFT JOIN "Membership" AS membership ON membership."instructorId" = instructor."id"
    JOIN "User" AS account
      ON account."id" = 'legacy-instructor-' || instructor."id"
      OR account."email" = 'legacy-instructor-' || md5(instructor."id") || '@unclaimed.courtly.invalid'
    WHERE membership."id" IS NULL
  ) THEN
    RAISE EXCEPTION 'Cannot create unclaimed instructor accounts: deterministic identity collision exists';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM "Instructor" AS instructor
    LEFT JOIN "Membership" AS membership ON membership."instructorId" = instructor."id"
    JOIN "Membership" AS collision
      ON collision."id" = 'legacy-membership-' || instructor."id"
    WHERE membership."id" IS NULL
  ) THEN
    RAISE EXCEPTION 'Cannot create unclaimed instructor memberships: deterministic identity collision exists';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM "Instructor" AS instructor
    LEFT JOIN "Membership" AS membership ON membership."instructorId" = instructor."id"
    WHERE membership."id" IS NULL
    GROUP BY md5(instructor."id")
    HAVING count(*) > 1
  ) THEN
    RAISE EXCEPTION 'Cannot create unclaimed instructor accounts: placeholder email collision exists';
  END IF;
END $$;

INSERT INTO "User" (
  "id", "businessId", "name", "email", "passwordHash", "role", "instructorId",
  "accountType", "phone", "parentName", "createdAt"
)
SELECT
  'legacy-instructor-' || instructor."id",
  instructor."businessId",
  instructor."name",
  'legacy-instructor-' || md5(instructor."id") || '@unclaimed.courtly.invalid',
  NULL,
  'COACH',
  instructor."id",
  'COACH',
  '',
  '',
  CURRENT_TIMESTAMP
FROM "Instructor" AS instructor
LEFT JOIN "Membership" AS membership ON membership."instructorId" = instructor."id"
WHERE membership."id" IS NULL;

INSERT INTO "Membership" (
  "id", "userId", "businessId", "role", "instructorId", "active", "createdAt"
)
SELECT
  'legacy-membership-' || instructor."id",
  'legacy-instructor-' || instructor."id",
  instructor."businessId",
  'COACH',
  instructor."id",
  instructor."active",
  CURRENT_TIMESTAMP
FROM "Instructor" AS instructor
LEFT JOIN "Membership" AS membership ON membership."instructorId" = instructor."id"
WHERE membership."id" IS NULL;

CREATE UNIQUE INDEX "Membership_userId_businessId_key" ON "Membership"("userId", "businessId");
CREATE UNIQUE INDEX "Membership_instructorId_key" ON "Membership"("instructorId");
CREATE INDEX "Membership_businessId_idx" ON "Membership"("businessId");

ALTER TABLE "Membership" ADD CONSTRAINT "Membership_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Membership" ADD CONSTRAINT "Membership_businessId_fkey"
  FOREIGN KEY ("businessId") REFERENCES "Business"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Membership" ADD CONSTRAINT "Membership_instructorId_fkey"
  FOREIGN KEY ("instructorId") REFERENCES "Instructor"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- Preserve each existing session's current workspace. The field stays nullable
-- for customer accounts and provider accounts that have no active membership.
ALTER TABLE "AuthSession" ADD COLUMN "activeMembershipId" TEXT;

UPDATE "AuthSession" AS session
SET "activeMembershipId" = membership."id"
FROM "Membership" AS membership
WHERE membership."userId" = session."userId";

CREATE INDEX "AuthSession_userId_idx" ON "AuthSession"("userId");
CREATE INDEX "AuthSession_activeMembershipId_idx" ON "AuthSession"("activeMembershipId");

ALTER TABLE "AuthSession" ADD CONSTRAINT "AuthSession_activeMembershipId_fkey"
  FOREIGN KEY ("activeMembershipId") REFERENCES "Membership"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- Existing customer rows remain unclaimed. No login or usable credential is
-- fabricated from a business-local contact record.
ALTER TABLE "Customer" ADD COLUMN "userId" TEXT;

CREATE UNIQUE INDEX "Customer_businessId_userId_key" ON "Customer"("businessId", "userId");
CREATE INDEX "Customer_userId_idx" ON "Customer"("userId");

ALTER TABLE "Customer" ADD CONSTRAINT "Customer_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- Account-backed bookings do not issue private management credentials. Keep
-- the columns nullable so existing credentialed participants remain usable.
ALTER TABLE "Participant"
  ALTER COLUMN "managementTokenHash" DROP NOT NULL,
  ALTER COLUMN "managementTokenExpiresAt" DROP NOT NULL;

-- Contract the old tenant-specific account fields only after their membership
-- and session data has been copied. Deleting a business now removes its
-- memberships while the global users and their sessions remain.
ALTER TABLE "User" DROP CONSTRAINT "User_businessId_fkey";
ALTER TABLE "User" DROP CONSTRAINT "User_instructorId_fkey";
DROP INDEX "User_businessId_idx";
DROP INDEX "User_instructorId_key";
ALTER TABLE "User"
  DROP COLUMN "businessId",
  DROP COLUMN "role",
  DROP COLUMN "instructorId";

COMMIT;
