'use client';
import { useState } from 'react';
import { ArrowRight, ArrowUpRight, CalendarDays, Check, ChevronLeft, ChevronRight, Clock3, Copy, CreditCard, ExternalLink, MapPin, Plus, Repeat2, Route, Sparkles, Users, Wallet } from 'lucide-react';
import { formatInTimeZone } from 'date-fns-tz';
import { Button } from '@/components/ui/button';
import type { Booking, Workspace } from '@/lib/types';
import { addDaysKey, dateKey, initials, money, shortDate, time } from '@/lib/utils';
import { toast } from 'sonner';

export function StatusBadge({ status, className = '' }: { status: string; className?: string }) { return <span className={`badge ${status.toLowerCase()} ${className}`}><span className={`h-1 w-1 rounded-full ${status === 'PENDING' ? 'bg-[#b19756]' : status === 'CANCELLED' ? 'bg-red-400' : 'bg-[#809a68]'}`} />{status === 'PENDING' ? 'Venue pending' : status.charAt(0) + status.slice(1).toLowerCase()}</span>; }
export function ScheduleList({ bookings, onSelect, data, compact = false }: { bookings: Booking[]; onSelect: (b: Booking) => void; data: Workspace; compact?: boolean }) {
  const sorted = [...bookings].sort((a, b) => a.startAt.localeCompare(b.startAt));
  return <div className={`schedule-list ${compact ? '!px-4 !py-3 md:max-h-[430px] md:overflow-y-auto' : ''}`}>{!sorted.length && <div className={`empty-state ${compact ? '!py-12' : ''}`}><CalendarDays size={27} /><h3>Your day has a little breathing room.</h3><p>No lessons scheduled for this date.</p></div>}{sorted.map((b, index) => {
    const locationIndex = data.locations.findIndex(l => l.id === b.locationId);
    const next = sorted.slice(index + 1).find(n => n.instructorId === b.instructorId);
    const travel = next && next.locationId !== b.locationId;
    const buffer = travel ? Math.max(data.locations.find(l => l.id === b.locationId)?.travelMinutes || 0, data.locations.find(l => l.id === next.locationId)?.travelMinutes || 0) : 0;
    return <div key={b.id}><div className={`schedule-row ${compact ? '!mb-2 !gap-3' : ''}`}><div className={`schedule-time ${compact ? '!basis-12 !pt-2.5 !text-[11px]' : ''}`}>{formatInTimeZone(b.startAt, data.business.timezone, 'h:mm')}<span className="ml-1 text-[9px]">{formatInTimeZone(b.startAt, data.business.timezone, 'a').toLowerCase()}</span></div><button className={`lesson-card ${['', 'blue', 'amber', 'purple'][Math.max(0, locationIndex) % 4]} ${compact ? '!rounded-lg !px-3.5 !py-2.5 max-sm:!grid max-sm:!grid-cols-[minmax(0,1fr)_auto] max-sm:!items-start max-sm:!gap-2' : ''}`} onClick={() => onSelect(b)}><div className="min-w-0"><div className="flex min-w-0 items-start gap-2"><p className="lesson-title min-w-0 break-words text-left leading-snug">{b.serviceName}</p>{b.recurringId && <Repeat2 size={11} className="mt-0.5 shrink-0 text-[#a2ac96]" />}</div><div className={`lesson-meta ${compact ? '!mt-1.5 !text-[11px]' : ''}`}><span className="min-w-0 break-words">{b.participants.length === 1 ? b.participants[0].name : `${b.participants.length} students`}</span><span className="text-[#c5ccba]">·</span><span className="flex min-w-0 items-center gap-1"><MapPin size={10} className="shrink-0" /><span className="truncate">{b.locationName}</span></span><span className="desktop-only text-[#c5ccba]">·</span><span className="desktop-only">{Math.round((+new Date(b.endAt) - +new Date(b.startAt)) / 60000)} min</span></div></div><div className="flex shrink-0 flex-col items-end gap-2 max-sm:gap-1.5"><StatusBadge status={b.status} className={compact ? '!text-[10px] max-sm:!px-1.5' : ''} /><div className="flex items-center gap-1.5"><span className="text-[10px] text-[#8f9988] max-sm:hidden">{b.instructorName.split(' ')[0]}</span><div className="tiny-avatar">{initials(b.instructorName)}</div></div></div></button></div>{travel && buffer > 0 && <div className={`travel-row ${compact ? '!mb-2 !ml-[60px] !text-[10px]' : ''}`}><Route size={12} /><span>{buffer} min travel buffer</span><span>→</span><span>{next.locationName}</span></div>}</div>;
  })}</div>;
}

export default function Dashboard({ data, onNavigate, onNew, onBooking }: { data: Workspace; onNavigate: (v: string) => void; onNew: () => void; onBooking: (b: Booking) => void }) {
  const isCoach = data.membership.role === 'COACH';
  const today = dateKey(new Date(), data.business.timezone);
  const [selectedDate, setSelectedDate] = useState(today);
  const [weekOffset, setWeekOffset] = useState(0);
  const [locationFilter, setLocationFilter] = useState('all');
  const dayOfWeek = Number(formatInTimeZone(new Date(), data.business.timezone, 'i'));
  const weekStart = addDaysKey(today, -((dayOfWeek + 6) % 7) + weekOffset * 7);
  const visibleBookings = isCoach ? data.bookings.filter(b => b.instructorId === data.user.instructorId) : data.bookings;
  const activeBookings = visibleBookings.filter(b => b.status !== 'CANCELLED');
  const todays = activeBookings.filter(b => dateKey(b.startAt, data.business.timezone) === today);
  const weekBookings = activeBookings.filter(b => dateKey(b.startAt, data.business.timezone) >= weekStart && dateKey(b.startAt, data.business.timezone) <= addDaysKey(weekStart, 6));
  const weeklyRevenue = isCoach ? 0 : data.payments.filter(p => dateKey(p.paidAt, data.business.timezone) >= weekStart && dateKey(p.paidAt, data.business.timezone) <= addDaysKey(weekStart, 6)).reduce((sum, p) => sum + p.amount, 0);
  const outstanding = isCoach ? 0 : activeBookings.reduce((sum, b) => sum + b.participants.filter(p => !p.paid && !p.packageId).reduce((s, p) => s + p.price, 0), 0);
  const outstandingCount = isCoach ? 0 : activeBookings.reduce((sum, b) => sum + b.participants.filter(p => !p.paid && !p.packageId).length, 0);
  const uniqueToday = new Set(todays.flatMap(b => b.participants.map(p => p.customerId))).size;
  const selectedBookings = activeBookings.filter(b => dateKey(b.startAt, data.business.timezone) === selectedDate && (locationFilter === 'all' || b.locationId === locationFilter));
  const recent = [...visibleBookings].filter(b => b.status !== 'CANCELLED' && new Date(b.endAt) >= new Date()).sort((a, b) => a.startAt.localeCompare(b.startAt)).slice(0, 4);
  const revenueDays = isCoach ? [] : Array.from({ length: 7 }, (_, i) => { const date = addDaysKey(weekStart, i); return data.payments.filter(p => dateKey(p.paidAt, data.business.timezone) === date).reduce((s, p) => s + p.amount, 0); });
  const maxRevenue = Math.max(...revenueDays, 1);
  const sessionDays = Array.from({ length: 7 }, (_, i) => { const date = addDaysKey(weekStart, i); return activeBookings.filter(b => dateKey(b.startAt, data.business.timezone) === date).length; });
  const maxSessions = Math.max(...sessionDays, 1);
  const pendingVenueBookings = activeBookings.filter(b => b.status === 'PENDING' && new Date(b.endAt) >= new Date());
  const assignedLocationIds = new Set(data.services.flatMap(service => service.locations.map(location => location.locationId)));
  const visibleLocations = isCoach ? data.locations.filter(location => assignedLocationIds.has(location.id)) : data.locations;
  const activeLocations = visibleLocations.filter(l => l.active);
  const hours = todays.reduce((sum, b) => sum + (+new Date(b.endAt) - +new Date(b.startAt)) / 3600000, 0);
  const weekHours = weekBookings.reduce((sum, b) => sum + (+new Date(b.endAt) - +new Date(b.startAt)) / 3600000, 0);
  function shiftWeek(direction: number) { setWeekOffset(value => value + direction); setSelectedDate(value => addDaysKey(value, direction * 7)); }
  async function copyLink() { try { await navigator.clipboard.writeText(`${window.location.origin}/book/${data.business.slug}`); toast.success('Your booking link is copied'); } catch { toast.error('Copy is unavailable. Open your booking page and copy the address.'); } }
  return <div className="mx-auto max-w-[1380px]">
    <header className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end">
      <div>
        <div className="eyebrow mb-2 flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-[#99aa79]" />{formatInTimeZone(new Date(), data.business.timezone, 'EEEE, d MMMM')}</div>
        <h1>Your day, in a good place<span className="text-[#95a57a]">.</span></h1>
        <p className="mt-1.5 text-[13px] text-[#7f8a7c]">Welcome back, {data.user.name.split(' ')[0]}. {todays.length ? `${todays.length} session${todays.length === 1 ? '' : 's'} on today’s agenda.` : 'Your schedule is clear today.'}</p>
      </div>
      <div className="flex items-center gap-2.5">
        {!isCoach && <Button variant="outline" className="desktop-only !text-[12px]" onClick={() => window.open(`/book/${data.business.slug}`, '_blank', 'noopener,noreferrer')}><ExternalLink size={14} />Booking page</Button>}
        <Button className="!text-[12px]" onClick={onNew}><Plus size={15} />New booking</Button>
      </div>
    </header>

    {!isCoach && !data.business.isDemo && (!data.locations.length || !data.services.length || !data.availability.length) && <section className="mt-5 rounded-xl border border-[#dce6d2] bg-[#eef4e6] p-4"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-center"><div><div className="flex items-center gap-2"><Sparkles size={16} className="text-[#829665]" /><h2>A few small steps. A whole new rhythm.</h2></div><p className="mt-1 text-[12px] text-[#718363]">Finish setup, then share your booking page.</p></div><div className="flex flex-wrap gap-2">{[{ id: 'locations', label: 'Add a location', done: data.locations.length > 0 }, { id: 'services', label: 'Create a service', done: data.services.length > 0 }, { id: 'availability', label: 'Set your hours', done: data.availability.length > 0 }].map((step, i) => <Button variant="outline" size="sm" key={step.id} onClick={() => onNavigate(step.id)}>{step.done ? <Check size={12} /> : <span className="text-[#94a280]">{i + 1}.</span>}{step.label}</Button>)}</div></div></section>}

    <section aria-label={isCoach ? 'Coach snapshot' : 'Business snapshot'} className="mt-5 grid grid-cols-2 gap-px overflow-hidden rounded-xl border border-[#e2e7df] bg-[#e2e7df] shadow-[0_1px_2px_rgba(25,52,38,0.02)] md:grid-cols-4">
      <Stat title="Today's sessions" value={String(todays.length).padStart(2, '0')} detail={`${hours % 1 ? hours.toFixed(1) : hours} teaching hours`} icon={<CalendarDays size={16} />} />
      {isCoach ? <Stat title="This week's sessions" value={String(weekBookings.length).padStart(2, '0')} detail={`${weekHours % 1 ? weekHours.toFixed(1) : weekHours} teaching hours`} icon={<Clock3 size={16} />} /> : <Stat title="This week's earnings" value={money(weeklyRevenue)} detail="Payments collected" icon={<Wallet size={16} />} />}
      <Stat title={isCoach ? 'Assigned students' : 'Students'} value={String(data.customers.length).padStart(2, '0')} detail={`${uniqueToday} booked today`} icon={<Users size={16} />} />
      {isCoach ? <Stat title="Availability" value={String(data.availability.length).padStart(2, '0')} detail="Weekly teaching windows" icon={<CalendarDays size={16} />} onClick={() => onNavigate('availability')} /> : <Stat title="Outstanding" value={money(outstanding)} detail={`${outstandingCount} unpaid session${outstandingCount === 1 ? '' : 's'}`} icon={<CreditCard size={16} />} onClick={() => onNavigate('payments')} />}
    </section>

    <div className="mt-5 grid items-start gap-5 lg:grid-cols-[minmax(0,1.65fr)_minmax(280px,0.78fr)]">
      <section className="panel overflow-hidden" aria-labelledby="today-agenda-heading">
        <div className="flex items-start justify-between gap-3 px-4 pb-3 pt-4 sm:items-center sm:px-5">
          <div><h2 id="today-agenda-heading" className="!text-[17px]">Today’s agenda</h2><p className="mt-1 text-[11px] text-[#8b9587]">Choose a day to see every lesson, venue, and travel buffer.</p></div>
          <div className="flex shrink-0 items-center rounded-lg border border-[#e7ebe3] bg-[#fafbf8]"><button aria-label="Previous week" className="inline-flex h-11 w-11 items-center justify-center rounded-md text-[#7d8978] hover:bg-white" onClick={() => shiftWeek(-1)}><ChevronLeft size={16} /></button><span className="hidden min-w-[108px] text-center text-[11px] font-medium text-[#657360] sm:inline">{formatInTimeZone(weekStart + 'T12:00:00+08:00', data.business.timezone, 'MMMM yyyy')}</span><span className="min-w-8 text-center text-[11px] font-medium text-[#657360] sm:hidden">{formatInTimeZone(weekStart + 'T12:00:00+08:00', data.business.timezone, 'MMM')}</span><button aria-label="Next week" className="inline-flex h-11 w-11 items-center justify-center rounded-md text-[#7d8978] hover:bg-white" onClick={() => shiftWeek(1)}><ChevronRight size={16} /></button></div>
        </div>
        <div className="week-strip !gap-1 !px-3 !pb-3 sm:!px-4">{Array.from({ length: 7 }, (_, i) => { const d = addDaysKey(weekStart, i); const count = activeBookings.filter(b => dateKey(b.startAt, data.business.timezone) === d).length; return <button key={d} aria-label={shortDate(d + 'T12:00:00+08:00', data.business.timezone)} aria-pressed={selectedDate === d} className={`day-cell !gap-1.5 !py-2 ${selectedDate === d ? 'selected' : ''}`} onClick={() => setSelectedDate(d)}><span className="text-[9px]">{['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'][i]}</span><span className="day-number !text-[17px]">{Number(d.slice(-2))}</span><span className="day-dots">{Array.from({ length: Math.min(count, 3) }, (_, j) => <i key={j} />)}</span></button>; })}</div>
        <div className="flex items-center justify-between gap-3 border-b border-[#f0f2ec] bg-[#fcfdfb] px-4 py-3 sm:px-5"><div className="flex items-center gap-2"><span className="text-[11px] font-semibold text-[#657260]">{selectedDate === today ? 'Today' : shortDate(selectedDate + 'T12:00:00+08:00', data.business.timezone)}</span><span className="rounded-full bg-[#eef2e9] px-2 py-0.5 text-[10px] text-[#718067]">{selectedBookings.length} session{selectedBookings.length === 1 ? '' : 's'}</span></div><select aria-label="Filter schedule location" className="!min-h-0 !w-auto !max-w-[150px] !border-0 !bg-transparent !p-0 !text-[11px] !font-medium !text-[#6f7c69]" value={locationFilter} onChange={e => setLocationFilter(e.target.value)}><option value="all">All locations</option>{visibleLocations.map(l => <option key={l.id} value={l.id}>{l.name}</option>)}</select></div>
        <ScheduleList bookings={selectedBookings} onSelect={onBooking} data={data} compact />
        <div className="flex items-center justify-between border-t border-[#eef0e9] px-4 py-3 sm:px-5"><button className="text-[11px] font-medium text-[#7c886f] hover:text-[#244f3a]" onClick={() => { setSelectedDate(today); setWeekOffset(0); }}>Jump to today</button><button className="subtle-link !text-[11px] !font-medium" onClick={() => onNavigate('calendar')}>Full calendar<ArrowRight size={13} /></button></div>
      </section>

      <aside className="grid gap-4 md:grid-cols-2 lg:grid-cols-1">
        <section className="panel overflow-hidden" aria-labelledby="attention-heading">
          <div className="flex items-center justify-between px-5 pb-3 pt-4"><div><p className="eyebrow !text-[9px]">ACTION CENTRE</p><h2 id="attention-heading" className="mt-1 !text-[16px]">Needs your attention</h2></div><span className={`h-2 w-2 rounded-full ${pendingVenueBookings.length || (!isCoach && outstandingCount) ? 'bg-[#c3a45f]' : 'bg-[#88a273]'}`} /></div>
          <div className="space-y-2 px-3 pb-3">
            {pendingVenueBookings.length > 0 && <button onClick={() => onNavigate('bookings')} className="flex w-full items-center gap-3 rounded-lg border border-[#eee5cd] bg-[#fbf8ef] p-3 text-left transition-colors hover:bg-[#f8f2e3]"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-[#f1e7cb] text-[#a68b4c]"><Clock3 size={15} /></span><span className="min-w-0 flex-1"><span className="block text-[12px] font-semibold text-[#6e6246]">{isCoach ? `${pendingVenueBookings.length} venue${pendingVenueBookings.length === 1 ? '' : 's'} pending` : `Confirm ${pendingVenueBookings.length} venue${pendingVenueBookings.length === 1 ? '' : 's'}`}</span><span className="mt-0.5 block text-[11px] text-[#95896c]">{isCoach ? 'An owner or administrator must confirm these sessions.' : 'Pending sessions still need a court.'}</span></span><ChevronRight size={15} className="text-[#ad9d77]" /></button>}
            {!isCoach && outstandingCount > 0 && <button onClick={() => onNavigate('payments')} className="flex w-full items-center gap-3 rounded-lg border border-[#e7eae2] bg-[#fafbf8] p-3 text-left transition-colors hover:bg-[#f4f6f1]"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-[#edf1e9] text-[#75876b]"><CreditCard size={15} /></span><span className="min-w-0 flex-1"><span className="block text-[12px] font-semibold">Review {money(outstanding)} outstanding</span><span className="mt-0.5 block text-[11px] text-[#889183]">Across {outstandingCount} unpaid session{outstandingCount === 1 ? '' : 's'}.</span></span><ChevronRight size={15} className="text-[#98a290]" /></button>}
            {!pendingVenueBookings.length && (isCoach || !outstandingCount) && <div className="rounded-lg bg-[#f2f6ee] px-4 py-5 text-center"><Check size={17} className="mx-auto text-[#79936b]" /><p className="mt-2 text-[12px] font-semibold">You’re all caught up.</p><p className="mt-1 text-[11px] text-[#829079]">{isCoach ? 'No venue follow-ups.' : 'No venue or payment follow-ups.'}</p></div>}
          </div>
          {!isCoach && <div className="border-t border-[#edf0e8] px-5 py-3"><div className="flex items-center justify-between gap-3"><div><p className="text-[11px] font-semibold">Your booking page</p><p className="mt-0.5 text-[10px] text-[#919a8b]">Ready to share with students.</p></div><div className="flex gap-1.5"><Button variant="outline" size="sm" className="!px-2.5 !text-[10px]" onClick={copyLink}><Copy size={12} />Copy link</Button><Button size="icon" variant="outline" aria-label="Preview booking page" onClick={() => window.open(`/book/${data.business.slug}`, '_blank', 'noopener,noreferrer')}><ExternalLink size={13} /></Button></div></div></div>}
        </section>

        <section className="panel overflow-hidden" aria-labelledby="up-next-heading">
          <div className="flex items-center justify-between px-5 pb-3 pt-4"><div><p className="eyebrow !text-[9px]">ON THE BOOKS</p><h2 id="up-next-heading" className="mt-1 !text-[16px]">Up next</h2></div><button className="subtle-link !text-[11px]" onClick={() => onNavigate('bookings')}>View all<ArrowUpRight size={13} /></button></div>
          <div className="border-t border-[#edf0e8]">{recent.slice(0, 3).map(b => { const paid = !isCoach && b.participants.every(p => p.paid || p.packageId); return <button key={b.id} className="flex w-full items-center gap-3 border-b border-[#f0f2ed] px-5 py-3 text-left last:border-b-0 hover:bg-[#fafbf8]" onClick={() => onBooking(b)}><div className="tiny-avatar !h-8 !w-8 !min-w-8 !bg-[#f0e9dc] !text-[9px] !text-[#8e7958]">{initials(b.participants[0]?.name || 'Group')}</div><div className="min-w-0 flex-1"><p className="truncate text-[12px] font-semibold">{b.serviceName}</p><p className="mt-1 truncate text-[10px] text-[#899286]">{b.participants[0]?.name || 'Group lesson'} · {formatInTimeZone(b.startAt, data.business.timezone, 'EEE, h:mm a')}</p></div>{!isCoach && <span className={`badge ${paid ? '' : 'pending'} !text-[9px]`}>{paid ? 'Paid' : 'Unpaid'}</span>}</button>; })}{!recent.length && <div className="empty-state !py-8">Your next great lesson starts with a booking.</div>}</div>
        </section>

        <section className="panel overflow-hidden md:col-span-2 lg:col-span-1" aria-labelledby="week-heading">
          <div className="flex items-center justify-between px-5 pb-2 pt-4"><div><p className="eyebrow !text-[9px]">WEEKLY PULSE</p><h2 id="week-heading" className="mt-1 !text-[16px]">This week, at a glance</h2></div><span className="rounded-md bg-[#f1f4ec] px-2 py-1 text-[10px] font-medium text-[#7b8872]">{formatInTimeZone(weekStart + 'T12:00:00+08:00', data.business.timezone, 'd')}–{formatInTimeZone(addDaysKey(weekStart, 6) + 'T12:00:00+08:00', data.business.timezone, 'd MMM')}</span></div>
          <div className="flex items-end gap-4 px-5 pb-4"><div className="shrink-0 pb-1"><p className="text-[21px] font-semibold tracking-[-0.5px]">{weekBookings.length}</p><p className="mt-0.5 text-[10px] text-[#8d9788]">sessions booked</p></div><div className="flex h-14 flex-1 items-end gap-1.5">{(isCoach ? sessionDays : revenueDays).map((amount, i) => <div key={i} className="flex h-full flex-1 flex-col items-center justify-end gap-1"><div className={`w-full max-w-8 rounded-t-sm ${i === dayOfWeek - 1 ? 'bg-[#55794f]' : 'bg-[#e3eadb]'}`} style={{ height: `${Math.max(3, amount / (isCoach ? maxSessions : maxRevenue) * 38)}px` }} title={isCoach ? `${['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'][i]}: ${amount} session${amount === 1 ? '' : 's'}` : `${['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'][i]}: ${money(amount)}`} /><span className="text-[8px] text-[#9aa293]">{['M', 'T', 'W', 'T', 'F', 'S', 'S'][i]}</span></div>)}</div></div>
          <div className="flex items-center justify-between border-t border-[#edf0e8] px-5 py-3"><span className="text-[10px] text-[#8d9788]">{isCoach ? 'Teaching time this week' : 'Collected this week'}</span><span className="text-[12px] font-semibold">{isCoach ? `${weekHours % 1 ? weekHours.toFixed(1) : weekHours} hours` : money(weeklyRevenue)}</span></div>
        </section>

        <section className="panel overflow-hidden md:col-span-2 lg:col-span-1" aria-labelledby="venues-heading">
          <div className="flex items-center justify-between px-5 pb-2 pt-4"><div><p className="eyebrow !text-[9px]">TODAY BY VENUE</p><h2 id="venues-heading" className="mt-1 !text-[16px]">Venue load</h2></div><button aria-label={isCoach ? 'Manage availability' : 'Manage locations'} className="subtle-link !text-[11px]" onClick={() => onNavigate(isCoach ? 'availability' : 'locations')}>{isCoach ? 'Availability' : 'Manage'}<ArrowUpRight size={13} /></button></div>
          <div className="flex gap-2 overflow-x-auto px-5 pb-4 pt-2">{activeLocations.slice(0, 4).map((location, i) => <button key={location.id} className={`min-w-[125px] flex-1 rounded-lg border p-3 text-left transition-colors ${locationFilter === location.id ? 'border-[#9caf8f] bg-[#f0f5eb]' : 'border-[#e7ebe3] bg-[#fafbf8] hover:bg-[#f5f7f2]'}`} onClick={() => { setLocationFilter(location.id); setSelectedDate(today); setWeekOffset(0); }}><span className={`mb-2 flex h-7 w-7 items-center justify-center rounded-md ${i % 3 === 1 ? 'bg-[#eaf0f3] text-[#819eae]' : i % 3 === 2 ? 'bg-[#f3eee1] text-[#ae965c]' : 'bg-[#eaf1e3] text-[#7f956e]'}`}><MapPin size={14} /></span><span className="block truncate text-[11px] font-semibold">{location.name}</span><span className="mt-1 block text-[10px] text-[#8c9687]">{todays.filter(b => b.locationId === location.id).length} today</span></button>)}{!activeLocations.length && (isCoach ? <div className="w-full rounded-lg border border-dashed border-[#dfe5dc] p-4 text-left text-[11px] text-[#879282]">No active venues are assigned to your services.</div> : <button className="w-full rounded-lg border border-dashed border-[#dfe5dc] p-4 text-left text-[11px] text-[#879282]" onClick={() => onNavigate('locations')}>Add your first place to teach <ArrowRight size={12} className="ml-1 inline" /></button>)}</div>
        </section>
      </aside>
    </div>

    <footer className="mt-5 flex items-center justify-between text-[10px] text-[#9ea699]"><span className="flex items-center gap-1.5"><span className="h-1 w-1 rounded-full bg-[#9faf87]" />All times in {data.business.timezone}{isCoach ? '' : ` · ${data.business.currency}`}</span><span className="desktop-only">More time for the game. That’s Courtly.</span></footer>
  </div>;
}
function Stat({ title, value, detail, icon, onClick }: { title: string; value: string; detail: string; icon: React.ReactNode; onClick?: () => void }) {
  const content = <><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-[11px] font-medium text-[#778273]">{title}</p><p className="mt-1.5 truncate text-[23px] font-semibold tracking-[-0.6px] text-[#263a30]">{value}</p></div><span className="stat-icon !h-8 !w-8 shrink-0">{icon}</span></div><div className="mt-1.5 flex items-center justify-between gap-2"><p className="truncate text-[10px] text-[#8d9788]">{detail}</p>{onClick && <ArrowUpRight size={12} className="shrink-0 text-[#829076]" />}</div></>;
  const className = "min-w-0 bg-white px-4 py-3.5 text-left sm:px-5 transition-colors";
  return onClick ? <button className={`${className} hover:bg-[#fafbf8]`} onClick={onClick}>{content}</button> : <div className={className}>{content}</div>;
}

export function CalendarView({ data, onNew, onBooking, listOnly = false }: { data: Workspace; onNew: () => void; onBooking: (b: Booking) => void; listOnly?: boolean }) {
  const [selectedDate, setDate] = useState(dateKey());
  const [instructor, setInstructor] = useState('all');
  const [location, setLocation] = useState('all');
  const [status, setStatus] = useState('all');
  const [view, setView] = useState<'day' | 'week'>('day');
  const selected = data.bookings.filter(b => (listOnly || view === 'week' ? true : dateKey(b.startAt) === selectedDate) && (instructor === 'all' || b.instructorId === instructor) && (location === 'all' || b.locationId === location) && (status === 'all' || b.status === status)).sort((a, b) => a.startAt.localeCompare(b.startAt));
  const weekStart = addDaysKey(selectedDate, -((new Date(`${selectedDate}T12:00:00+08:00`).getUTCDay() + 6) % 7));
  return <><div className="section-heading"><div><div className="eyebrow mb-2">EVERY LESSON, IN SYNC</div><h1>{listOnly ? 'Bookings' : 'Your calendar'}</h1><p className="mt-2 text-xs text-stone-400">One schedule. Every instructor. Every place you play.</p></div><Button onClick={onNew}><Plus size={14} />New booking</Button></div><div className="mb-5 flex flex-wrap items-center gap-3">{!listOnly && <><div className="flex items-center gap-2"><Button size="icon" variant="outline" aria-label="Previous date" onClick={() => setDate(addDaysKey(selectedDate, view === 'week' ? -7 : -1))}><ChevronLeft size={15} /></Button><input type="date" aria-label="Calendar date" className="!w-auto" value={selectedDate} onChange={e => setDate(e.target.value)} /><Button size="icon" variant="outline" aria-label="Next date" onClick={() => setDate(addDaysKey(selectedDate, view === 'week' ? 7 : 1))}><ChevronRight size={15} /></Button><Button variant="outline" size="sm" onClick={() => setDate(dateKey())}>Today</Button></div><div className="tab-bar"><button onClick={() => setView('day')} className={view === 'day' ? 'active' : ''}>Day</button><button onClick={() => setView('week')} className={view === 'week' ? 'active' : ''}>Week</button></div></>}
    <select aria-label="Filter instructor" className="!w-auto !text-xs" value={instructor} onChange={e => setInstructor(e.target.value)}><option value="all">All instructors</option>{data.instructors.map(i => <option key={i.id} value={i.id}>{i.name}</option>)}</select><select aria-label="Filter location" className="!w-auto !text-xs" value={location} onChange={e => setLocation(e.target.value)}><option value="all">All locations</option>{data.locations.map(l => <option key={l.id} value={l.id}>{l.name}</option>)}</select><select aria-label="Filter booking status" className="!w-auto !text-xs" value={status} onChange={e => setStatus(e.target.value)}><option value="all">All statuses</option><option value="CONFIRMED">Confirmed</option><option value="PENDING">Venue pending</option><option value="CANCELLED">Cancelled</option><option value="COMPLETED">Completed</option></select></div>
    {listOnly ? <section className="panel table-wrap"><table className="data-table"><thead><tr><th>Lesson</th><th>Student</th><th>When</th><th>Location</th><th>Instructor</th><th>Status</th></tr></thead><tbody>{selected.map(b => <tr key={b.id} onClick={() => onBooking(b)} className="cursor-pointer hover:bg-stone-50"><td className="font-medium">{b.serviceName}</td><td>{b.participants.map(p => p.name).join(', ')}</td><td>{shortDate(b.startAt)}<p className="mt-1 text-[10px] text-stone-400">{time(b.startAt)} – {time(b.endAt)}</p></td><td>{b.locationName}</td><td>{b.instructorName}</td><td><StatusBadge status={b.status} /></td></tr>)}</tbody></table>{!selected.length && <div className="empty-state">No bookings match your filters.</div>}</section> : view === 'day' ? <section className="panel max-w-4xl"><div className="panel-heading"><h2>{shortDate(selectedDate + 'T12:00:00+08:00')}</h2><span className="text-xs text-stone-400">{selected.length} sessions</span></div><ScheduleList bookings={selected} data={data} onSelect={onBooking} /></section> : <section className="panel overflow-x-auto"><div className="grid min-w-[900px] grid-cols-7">{Array.from({ length: 7 }, (_, i) => { const day = addDaysKey(weekStart, i); return <div key={day} className="min-h-[500px] border-r border-stone-100 last:border-0"><div className={`border-b border-stone-100 px-3 py-5 text-center text-xs ${day === dateKey() ? 'bg-[#eaf0e5]' : ''}`}>{shortDate(day + 'T12:00:00+08:00')}</div><div className="space-y-2 p-2">{selected.filter(b => dateKey(b.startAt) === day).map(b => <button key={b.id} onClick={() => onBooking(b)} className="w-full rounded-lg border border-[#e0e8d7] bg-[#f3f7ee] p-3 text-left"><p className="text-[9px] text-[#859775]">{time(b.startAt)}</p><p className="mt-2 text-[11px] font-semibold">{b.serviceName}</p><p className="mt-2 text-[9px] text-[#859775]">{b.locationName}</p><p className="mt-1 text-[9px] text-[#859775]">{b.instructorName}</p>{b.status === 'PENDING' && <span className="badge pending mt-2">Venue pending</span>}</button>)}</div></div>; })}</div></section>}
  </>;
}
