import EmbeddedPostgres from 'embedded-postgres';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
const directory = fileURLToPath(new URL('../.data/postgres', import.meta.url));
const pg = new EmbeddedPostgres({ databaseDir: directory, user: 'postgres', password: 'courtly_local_dev', port: 55432, persistent: true, postgresFlags: ['-h', '127.0.0.1'], onLog: (line) => process.stdout.write(String(line) + '\n') });
if (!existsSync(`${directory}/PG_VERSION`)) await pg.initialise();
await pg.start();
const client = pg.getPgClient();
await client.connect();
const result = await client.query("SELECT 1 FROM pg_database WHERE datname = 'courtly'");
if (!result.rowCount) await client.query('CREATE DATABASE courtly');
await client.end();
console.log('Local PostgreSQL ready on 127.0.0.1:55432. Data persists in .data/postgres.');
for (const signal of ['SIGINT', 'SIGTERM']) process.on(signal, async () => { await pg.stop(); process.exit(0); });
setInterval(() => {}, 60_000);
